### ISSUE TITLE
Statikus analízis eszköz futtatása

### ISSUE THREAD

**Issue by pozdi** [BME-MIT-IET/Bugsweeper-iet-2018#4]
Codacy vagy FindBugs

**Comment by pozdi** [comment]
Codacy szerint ezeket a hibák fordulnak elő:
-  Switch statements should have a default label
- Method names should not contain underscores
- Method names should not contain underscores

**Comment by pozdi** [comment]
nincsenek nagy hibák, csak formaságok, pl nem használt kódrészletek (21db), vagy hibaérzékeny kódok (ebből kicsit több, de nem tűnnek veszélyesnek 😄), ezekkel nem tudom mennyire kéne foglalkozni..

**Comment by krisshepherd** [comment]
Szerintem akkor egy ilyen "method names should not contain underscores" refactort lehet tolni, azt egy gyors Jobb Click -> Refactor -> Rename (Shift+F6) megoldja. Annyi még, hogy szerintem csináljatok egy külön branch-et neki, aztán a végén legyen egy pull+merge :)

**Comment by pozdi** [comment]
codacy integrálva a github projekthez, collaborators hozzáadva a projekthez

**Comment by krisshepherd** [comment]
Pull request review megvolt. Egyből toltam is egy merge-et, úgyhogy ki lehet törölni a fölösleges branch-et majd.
